version: '3.8'

services:
  tg_bot:
    build:
      context: .
      dockerfile: tg_bot/Dockerfile
    volumes:
      - ./tg_bot:/app
      - ./core:/app/core   # Добавлено монтирование папки core в tg_bot
    env_file:
      - ./tg_bot/.env
    networks:
      - teamsearch_network

  admin:
    build:
      context: .
      dockerfile: admin/Dockerfile
    volumes:
      - ./admin:/app
      - ./core:/app/core  # Монтируем папку core в admin
    networks:
      - teamsearch_network

networks:
  teamsearch_network:
    driver: bridge

