# Generated by Django 5.1.3 on 2024-11-25 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_invite_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invite',
            old_name='user_id',
            new_name='user',
        ),
    ]
